version: '3.8'

services:
  smart-insights:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeassistant-smart-insights-prod
    ports:
      - "80:80"
    environment:
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_INFLUXDB_URL=${VITE_INFLUXDB_URL}
      - VITE_INFLUXDB_TOKEN=${VITE_INFLUXDB_TOKEN}
      - VITE_INFLUXDB_ORG=${VITE_INFLUXDB_ORG}
      - VITE_INFLUXDB_BUCKET=${VITE_INFLUXDB_BUCKET}
      - VITE_HOMEASSISTANT_URL=${VITE_HOMEASSISTANT_URL}
      - VITE_HOMEASSISTANT_TOKEN=${VITE_HOMEASSISTANT_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - smart-insights-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smart-insights.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.smart-insights.tls=true"
      - "traefik.http.routers.smart-insights.tls.certresolver=letsencrypt"
      - "traefik.http.services.smart-insights.loadbalancer.server.port=80"

  # Reverse proxy with SSL
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - smart-insights-network
    restart: unless-stopped

  # Optional: InfluxDB for complete stack
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb-prod
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=homeassistant
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - smart-insights-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.your-domain.com`)"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.routers.influxdb.tls.certresolver=letsencrypt"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"

networks:
  smart-insights-network:
    driver: bridge

volumes:
  influxdb_data:
  letsencrypt: 